server.port=${PORT:5000}

spring.application.name=secure-webapp-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/securewebapp}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

APP_SEED_ENABLED=${APP_SEED_ENABLED:false}
APP_SEED_USERNAME=${APP_SEED_USERNAME:}
APP_SEED_PASSWORD=${APP_SEED_PASSWORD:}

logging.level.org.springframework.security=INFO
